### ISSUE TITLE
onUserLoginAuthorize is not implemented ?

### ISSUE THREAD

**Issue by sbancal** [trilbymedia/grav-plugin-login-ldap#15]
Hi,

I couldn't make *grav-plugin-login-ldap* work up to the moment I found that *grav-plugin-login* fires the event `onUserLoginAuthorize` at https://github.com/getgrav/grav-plugin-login/blob/5ee21643ad8adbc3af7c3e0e04947d9cd7426481/classes/Login.php#L121 and it fails.

I'm really not sure, but since it's mentioned in https://github.com/getgrav/grav-plugin-login/blob/master/CHANGELOG.md on v3.3.0 , this seems to have changed recently.

Does that mean that *grav-plugin-login-ldap* has to implement something in order to make this event succeed, with no 2FA?

**Comment by ghost** [comment]
Same problem here. I've installed grav on an Ubuntu 20.04 and setup ldap-login to bind to an Active Directory (Windows server 2019) and after a while (see #7 for details on how to bind and map fields), the plugin still says "Login failed...".

By adding dumps on same "classes/Login.php" file, I saw that :

1. On line 111, the event is full of values and the user is correctly set up,
2. On line 124, the event is almost empty and the user have been removed.

The only listener I found for onUserLoginAuthorize is in the Login plugin (there is nothing in the Ldap-login plugin).

**Comment by w00fz** [comment]
@mahagr this seems to be an issue introduced after the revamp of the events to better accommodate 2FA. 

This could be potentially affecting OAuth as well, not just LDAP.

**Comment by mahagr** [comment]
`onUserAuthorize` doesn't do anything else but checks if user has access to login either to the site or admin.

So you just need to set either user groups or user access and it should just work.

I don't have LDAP server available, but if you look at https://github.com/getgrav/grav-plugin-login/blob/5ee21643ad8adbc3af7c3e0e04947d9cd7426481/classes/Login.php#L118 and dump the user object there, you should see if it has any groups or access set up.

**Comment by mahagr** [comment]
Link for myself as I don't have LDAP server: https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/

**Comment by ghost** [comment]
I've just do the dump with a fresh install (1.6.26 Grav core + admin plugin and then install the login-ldap plugin). I've only setup the "configuration" panel of the plugin (advanced is left intact). Here is the code I've inserted in the login class as you suggested :

```php
echo "<pre>" ;
print_r($user->groups) ;
echo "---\n" ;
print_r($user->access) ;
echo "</pre>" ;
exit() ;
```

And then, this is the result with valid credentials :

```
Array
(
    [0] => ldap_users
)
---
Array
(
    [site] => Array
        (
            [login] => true
        )
)
```

On line 124, the event is now full of values and the status is "33" which, applying the flags seems to tell that it is a success but authorisation is denied.

**Comment by mahagr** [comment]
No, it says that authentication succeeded, but authorization did not. Are you trying to log into admin? Because of then you need to have an access rule:

```yaml
access:
  admin:
    login: true
```

To do this, you need to create a group for users who are allowed to log into admin in both ldap and Grav site and inside Grav you should set the access to the user group to get into admin.

**Comment by ghost** [comment]
Yes, I'd like to let ldap/AD users to login to the admin panel. With your explanations, I've added a root element to the "groups access level" :

```
ad_group_name_here:
    admin:
      login: true
```

And now, I'am able to connect to the admin pannel 😄 

Unfortunately, when I log out, I get and exception :

```php
        if (false === $this->search) {
            throw new LdapException(sprintf('Could not complete search with dn "%s", query "%s" and filters "%s".', $this->dn, $this->query, implode(',', $this->options['filter'])));
        }
```

Due to `login-ldap.php` (line 137) trying to do an LDAP query. The exception is present in the browser where I disconnected (in my test, chrome, call it A), any other one (in my test, edge, call it B) but I can still use the admin pannel on a browser where I had a valid opened session (with the local admin actound, firefox for me, call it C).

I can disable the plugin (with browser C), then refresh the admin pannel on the other browser (A/B) and there is no more exception. I can then re-enable the plugin (with C) and on the other browser (A/B), I no longer have the exception and I can login with ldap acount.

I don't know if it deserve a specific issue, feel free to move this comment.

**Comment by mahagr** [comment]
It may be a good idea to create a new issue with a proper title. Unfortunately, I'm not familiar with LDAP plugin so let's hope someone who knows more about the plugin.

**Comment by ghost** [comment]
The commit mentionned in the #14 ticket fixe the problem when user log out. Just wait to be released ;-)

**Comment by rhukster** [comment]
released
